DROP INDEX normalized_membership_number_index;
DROP INDEX normalized_last_name_index;
DROP INDEX normalized_first_name_index;
DROP INDEX normalized_last_name_first_name_index;
DROP INDEX normalized_first_name_last_name_index;
