name: Wasm

on:
  push:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./wasm

    steps:
      - uses: actions/checkout@v4
      - name: Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-build-wasm-22.04"
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli || true
      - name: Build
        run: cargo build --target=wasm32-unknown-unknown --verbose
      - name: Generate bindings
        run: wasm-bindgen --target=web --out-dir=pkg target/wasm32-unknown-unknown/debug/wasm.wasm

  clippy:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./wasm

    steps:
      - uses: actions/checkout@v4
      - name: Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-clippy-wasm-22.04"
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - name: Clippy
        run: cargo clippy

  tests:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./wasm

    steps:
      - uses: actions/checkout@v4
      - name: Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-tests-wasm-22.04"
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install wasm-bindgen-cli & wasm-pack
        run: cargo install wasm-bindgen-cli wasm-pack || true
      - name: Run tests
        run: wasm-pack test --headless --firefox
